before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3
language: go
go:
- 1.7.1
before_install:
- go get gopkg.in/yaml.v2
- go get github.com/docker/libcompose
- go get golang.org/x/net/context
script:
- "./build_test.sh"
env:
  global:
  - secure: "sAv5uAiQjAf6kRYdbpGgnfDBBofu3UO+SALstLAIAWbqfNR7NgMmgjSWNIMyOuaABYTTCOUrgGRY2+ff+lSjz7ClHApOM7VK4u65mVD6bg0yFPDiMCAf+Alit1rqZSsBESuqJ5qs2UucFRzgPt0ypRmyvY0GUlgd48Yi9vNJZnaORYE02GdctcdtzhF+W0IOTDCIcyk3ZrA0ch3d/hh3VBMZxNma72BC2AClnPyVZsWOljN+pxkW+91vlLF6QQUO6nFkUJ2OQAFtZ4lRjgukZZbX5MJqeuj/OVF+nuWlytadf4ubbU+/UHVy7YeDxYdSEJOgsk7NEheZ6+SJ8Vk1wm/DD5EkMkrhzNr5eQyoOKWzYk4SLBM1lovB5ZYdN1vA6xx14U0o0FlMxOTrwrw67zl3M1yto1nJfzwrb6Kfsj+PVS6lE60pNd58Hfdm3/T76QkDVfyBZlrRdGcy982AKtzgzXhoCKa3aY3XXVUHiJsqupHa0dipMpk8lo3V+6AkilrGRtot5rVA/WSLLYv6mDbmZ6o7ryFu1UU0vgrUwC4BiGjaqtzNiUNRH7pF1h1/0l6nKToH8ir3jjZvO63pqtb9fPywpgCsRy9mzn1JVsXqaKQWh0xb1+j5K6S8M/F61odahZwfae3y86uXjjskqsFCMqMMYEcDlhzPCSpKJhw="
  - secure: "dZ0loBDToNjC5tfpwHKUQWDx0cbQvV39NTFVNk7sB6Dijt3ut3vK+o6VBUfc/h6/nz1V34uxhAsqrYmjHP1vN3Q/imRLaHGhelZawUhyUQXsPuYxEtBuwi7OKlJSC2flxU56xjiJyTmqV7jBTiLQIPfBxC/oBX8kErRda6JQYLdQ10P3Hb94PUCBuOur+EHGlBVftd2jx21UqiwNd52YLi+dIWZxe4mqHuwU5YSKRFSGhrhKtl0vS7NQsbxZ4oJMcwZl12fTJ4CxwArL53eUuk0Iiq3942akP/wM85EAk1EzTjiqKWI4LiLW+ViUlKD4r9XgT9/+u9JnC8q0L0Jt2T9L+NRKBFdJIGdRKwr6DYqrSFke3W/u3SeTb0vp86nbnFWgbJ9kUkk8iBj/Jji7DU0Jo+ttoOcDSBIFSDfb580bliTIQAXcbIuK0Gsocjf+cg7cHLC5Wp9SYRl9+zZsCIG8/WR7gHk5TGPy2BDAl0nXHpeMhpZjYId+yXNZir1xlqUdReyLNNnocZbBxRiLxilN1qGDlw7+J+riVBeSx3fnBud3VpivtlxzkKCJvUbYNFnJIwf2NgqG9wJK0f8g41goLDtJ2elHPoYg4jUEB9VQ+px0MeuRTTeySBGKNIppd6xuNvJI3bHpQg39TbY1Ly+Kqtr349XUlOvRyMpWInw="
