language: go
go:
- 1.7.1
before_install:
- go get gopkg.in/yaml.v2
- go get github.com/docker/libcompose
- go get golang.org/x/net/context
script:
- "./build_test.sh"
deploy:
  provider: bintray
  file: fli-docker.json
  key:
    secure: yCkULVJUz8AN3Fp6e3viAuEssbjJlRZihyKA/h36k5S1GVy4Z6a8c3zgLXkYDMz51JNitWN/DqpK9/Rf3pykM51pekTRFtgmhAWYotJL9Pebf9LPbJMrscR4ouGY4/Klba/5uA3dSdeSbdLUgofn/cA5gmwAI+0xXcDql29RzmkPPEc/y1AjCD6+NeW/7a/yjH8EnOZ4/QMF/kbezyFFkfbIb4zwEdJhmlzbPIqodBA4xkioo9ZNcbyJX3XiDaQNKKteRgsnEFjpNLyds4V/ngn7LZxgDzMg4wSZsb0/yLHtG8RPltL0zO+ZveapkpEkoZ0CLqu9jQ/SE0B7N4uZRa8VZ2dMLvE+2MdRB/+aCwpws2TPoFzxfByiidJcQ2s4yLo33PHaB8POg/u6fIkIqHjlcj5YSqrgJrLhur5s1BIOj29jA0oXie+txUhbNT7rUOaaEhPgoFHqBbGTYCVCTLCG6ATwepJ0/cOU/Vh//8JURWibEKeBN2FH/S1Ecoa3xAvDvqE61mDkIVXdCdL0qTmusZHZtH3j1ZBjLLhytVc1G9/6RUbWOh6RGqet7iA3AJ+i+wnPBEkriwxggceYzBzFitDm1wpphNFOYYbQVV1T3Mixb7eFt6KeT9oLlYjIwVTHoJsdnmXzLtjnWVAygauPEUPMC/WhttCwxTb39/w=
  user: wallnerryan
  on:
    all_branches: true
